// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6bMJgR-z75U5-8tWiILAAg2oBMna_es',
    appId: '1:615215418130:web:3c6f436a1b5ade586201cb',
    messagingSenderId: '615215418130',
    projectId: 'prueba-2-ll',
    authDomain: 'prueba-2-ll.firebaseapp.com',
    databaseURL: 'https://prueba-2-ll-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-2-ll.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgbpVPgispoij_jMvt6xfyKF6yu_h2OUk',
    appId: '1:615215418130:android:4e950397564568296201cb',
    messagingSenderId: '615215418130',
    projectId: 'prueba-2-ll',
    databaseURL: 'https://prueba-2-ll-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-2-ll.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDaq2CbxD92dsA8wxQ4HXN3sucHivKsw',
    appId: '1:615215418130:ios:ee68aefb3980fb6b6201cb',
    messagingSenderId: '615215418130',
    projectId: 'prueba-2-ll',
    databaseURL: 'https://prueba-2-ll-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-2-ll.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDaq2CbxD92dsA8wxQ4HXN3sucHivKsw',
    appId: '1:615215418130:ios:ee68aefb3980fb6b6201cb',
    messagingSenderId: '615215418130',
    projectId: 'prueba-2-ll',
    databaseURL: 'https://prueba-2-ll-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-2-ll.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh6bMJgR-z75U5-8tWiILAAg2oBMna_es',
    appId: '1:615215418130:web:94c3feebe60250bc6201cb',
    messagingSenderId: '615215418130',
    projectId: 'prueba-2-ll',
    authDomain: 'prueba-2-ll.firebaseapp.com',
    databaseURL: 'https://prueba-2-ll-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-2-ll.appspot.com',
  );
}
